routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->group( function() {
    Route::resource('atividades', 'AtividadesController');
    Route::resource('recursos', 'RecursosController');
});

resources/views/home.blade.php
@extends('layouts.app') 

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 mx-auto">
            <b-breadcrumb :items="{{$breadcrumbList}}"></b-breadcrumb>
			<panel-component
                title="Dashboard"
                color="dark">
				<div class="row">
					<div class="col-md-4">
                        <card-info-component 
                            title="Recursos"
                            color="danger"
                            count="10"
                            url="{{ route('recursos.index') }}"
                            icon="ion ion-settings">
						</card-info-component>
					</div>
					<div class="col-md-4">
                        <card-info-component 
                            title="Atividades"
                            color="info"
                            count="10"
                            url="{{ route('atividades.index') }}"
                            icon="ion ion-navicon-round">
						</card-info-component>
					</div>
				</div>
			</panel-component>
		</div>
	</div>
</div>
@endsection