routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->group( function() {
    Route::resource('atividades', 'AtividadesController');
    Route::resource('recursos', 'RecursosController');
});

app/Recurso.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Recurso extends Model
{
    protected $fillable = ['descricao', 'quantidade', 'observacao'];
}

app/Http/Controllers/Admin/RecursosController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

use App\Recurso;
use App\Atividade;

class RecursosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $breadcrumbList = json_encode([
            [
                "text" => "Home",
                "href" => route('home')
            ],
            [
                "text" => "Artigos",
                "active" => true
            ]
        ]);

        $recursos = (Recurso::select('id', 'descricao', 'quantidade', 'observacao')->get());

        $recursosList = array();
        foreach($recursos as $value) {
            $atividade = array(
                "id" => $value['id'],
                "descricao" => $value['descricao'],
                "quantidade" => $value['quantidade'],
                "observacao" => $value['observacao'],
                "status" => ($value['quantidade'] > 0 ? "Recurso Disponível" : "Recurso Indisponível")
            );
            array_push($recursosList, $atividade);
        }
        $recursosList = json_encode($recursosList);

        return view(
            'admin.recursos.index',
            compact('breadcrumbList', 'recursosList')
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breadcrumbList = json_encode([
            [
                "text" => "Home",
                "href" => route('home')
            ],
            [
                "text" => "Recursos",
                "href" => route('recursos.index')
            ],
            [
                "text" => "Novo",
                "active" => true
            ]
        ]);
        return view(
            'admin.recursos.create',
            compact('breadcrumbList')
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $validation = Validator::make($data, [
            'descricao' => 'required',
            'observacao' => 'required',
            'quantidade' => 'required',
        ]);

        if ($validation->fails()) {
            return redirect()->back()->withErrors($validation)->withInput();
        }
        
        Recurso::create($data);

        return redirect()->route('recursos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $recurso = Recurso::find($id);

        $breadcrumbList = json_encode([
            [
                "text" => "Home",
                "href" => route('home')
            ],
            [
                "text" => "Recursos",
                "href" => route('recursos.index')
            ],
            [
                "text" => "Editar",
                "active" => true
            ]
        ]);
        return view(
            'admin.recursos.create',
            compact('breadcrumbList', 'recurso')
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        if(isset($data["tipo"])){
            $quantidade = $data["quantidade"];
            $recurso = Recurso::find($id);

            $atividade = new Atividade();
            $atividade->user_id = \Auth::user()->id;
            $atividade->recurso_id = $id;
            $atividade->quantidade = $quantidade;
            
            if($data["tipo"] == "entrada") {
                $atividade->tipo = 1;
                $recurso->quantidade += $quantidade;
                $atividade->save();
            } else if ($data["tipo"] == "saida") {
                if($recurso->quantidade >= $quantidade) {
                    $recurso->quantidade -= $quantidade;
                    $atividade->tipo = 2;
                    $atividade->save();
                }
            }
            $recurso->save();
        } else {
            $validation = Validator::make($data, [
                'descricao' => 'required',
                'observacao' => 'required',
            ]);

            if ($validation->fails()) {
                return redirect()->back()->withErrors($validation)->withInput();
            }
            
            Recurso::find($id)->update($data);
        }

        return redirect()->route('recursos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Recurso::find($id)->delete();

        return response()->json(['success' => 'success'], 204);
    }
}

resources/views/admin/recursos/create.blade.php
@extends('layouts.app') @section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 mx-auto">
			<b-breadcrumb :items="{{$breadcrumbList}}"></b-breadcrumb>
			<panel-component title="Novo recurso" color="dark">
				<form-component method="{{empty($recurso) ? 'POST' : 'PUT'}}" action="{{empty($recurso) ? route('recursos.store') : route('recursos.update', $recurso->id) }}" token="{{ csrf_token() }}">
					<div class="form-group">
						<label for="descricaoInput">Descrição</label>
						<input type="text" name="descricao" class="form-control" id="descricaoInput" value="{{ old('descricao', (!empty($recurso) ? $recurso->descricao : '')) }}"
						 placeholder="Digite a descrição">
						@if ($errors->has('descricao'))
						<label for="descricaoInput" class="form-text small text-danger">{{$errors->first('descricao')}}</label>
						@endif
					</div>
                    @if(empty($recurso))
                    <div class="form-group">
						<label for="quantidadeInput">Quantidade</label>
						<input type="number" name="quantidade" class="form-control" id="quantidadeInput" value="{{ old('quantidade', (!empty($recurso) ? $recurso->quantidade : '')) }}"
						 placeholder="Digite a quantidade">
						@if ($errors->has('quantidade'))
						<label for="quantidadeInput" class="form-text small text-danger">{{$errors->first('quantidade')}}</label>
						@endif
					</div>
                    @endif
					<div class="form-group">
						<label for="observacaoTextarea">Observação</label>
						<textarea name="observacao" class="form-control" id="observacaoTextarea" rows="3" placeholder="Observação...">{{ old('observacao', (!empty($recurso) ? $recurso->observacao : '')) }}</textarea> 
						@if ($errors->has('observacao'))
						<label for="observacaoTextarea" class="form-text small text-danger">{{$errors->first('observacao')}}</label>
						@endif
					</div>
					<button type="submit" class="btn btn-primary btn-block">Enviar</button>
				</form-component>
			</panel-component>
		</div>
	</div>
</div>
@endsection

resources/views/admin/recursos/index.blade.php
@extends('layouts.app') @section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 mx-auto">
			<b-breadcrumb :items="{{ $breadcrumbList }}"></b-breadcrumb>
			<panel-component title="Lista de recursos" color="dark">
                <table-page
                    v-bind:titles="['#','Descrição', 'Quantidade', 'Observação', 'Status']"
                    v-bind:items="{{ $recursosList }}"
					url="{{route('recursos.index')}}"
					token="{{ csrf_token() }}"
					estoque="true"></table-page>
			</panel-component>
		</div>
	</div>
</div>
@endsection